package routes

const (
	Images            = "images"
	TokenValidation   = "token/validate"
	Login             = "user/login"
	Status            = "status/"
	Search            = "search?query = "
	Entity            = "get/"
	SearchByAttribute = "attribute/"
	Links             = "links/"
	Relations         = "relations/"
	Add               = "add"
	AddBatch          = "add-batch"
	Delete            = "delete"
	Update            = "update"
	Append            = "append"
	Terminate         = "terminate"
	Upload            = "upload"
	NormalizeLocation = "normalize/location"
	NormalizeName     = "normalize/name"
	Normalize         = "normalize"
	UserRegister      = "user/register"
	ReaderRegister    = "reader/register"
	PublishTwitter    = "publish/twitter"
)
